apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  config.yaml: |
    extensions:
      file_storage/persistent_queue:
        directory: /var/lib/otelcol/file_storage
        create_directory: true
        timeout: 1s
        compaction:
          directory: /var/lib/otelcol/file_storage/compaction
          max_transaction_size: 65536

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      kubeletstats:
        endpoint: "https://${env:HOST_IP}:10250"
        insecure_skip_verify: true
        auth_type: serviceAccount

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 60
        spike_limit_mib: 12
      
      batch:
        send_batch_size: 1000
        timeout: 10s

      tail_sampling:
        decision_wait: 10s
        num_traces: 1000
        expected_new_traces_per_sec: 10
        policies:
          - name: keep-errors
            type: status_code
            status_code: {status_codes: [ERROR]}
          - name: keep-slow
            type: latency
            latency: {threshold_ms: 500}
          # No other policies -> implies drop the rest

      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.container.name
            - k8s.namespace.name
            - k8s.node.name
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
          - sources:
              - from: connection

      transform:
        metric_statements:
          - context: resource
            statements:
              - set(attributes["pod"], attributes["k8s.pod.name"]) where attributes["k8s.pod.name"] != nil
              - set(attributes["container"], attributes["k8s.container.name"]) where attributes["k8s.container.name"] != nil
              - set(attributes["namespace"], attributes["k8s.namespace.name"]) where attributes["k8s.namespace.name"] != nil
              - set(attributes["node"], attributes["k8s.node.name"]) where attributes["k8s.node.name"] != nil


    exporters:
      otlp/hub:
        endpoint: "jaeger.monitoring-hub.svc.cluster.local:4317"
        tls:
          insecure: true
        sending_queue:
          enabled: true
          storage: file_storage/persistent_queue # Use the extension
          queue_size: 5000 # Items, effectively limited by disk if persistent
      
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true # Critical for labels!


      otlphttp/loki:
        endpoint: "http://loki.monitoring-hub.svc.cluster.local:3100/otlp"
        tls:
          insecure: true

      debug:
        verbosity: detailed

    service:
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
      extensions: [file_storage/persistent_queue]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, tail_sampling, batch]
          exporters: [otlp/hub]
        metrics:
          receivers: [otlp, kubeletstats]
          processors: [k8sattributes, transform, memory_limiter, batch]
          exporters: [prometheus, debug]
        logs:
          receivers: [otlp]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [otlphttp/loki, debug]
