apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s

patches:
  - path: patches/otelcol-hostpath.yaml
    target:
      kind: DaemonSet
      name: otel-collector
  - path: patches/grafana-nodeport.yaml
    target:
      kind: Service
      name: grafana
  - path: patches/jaeger-nodeport.yaml
    target:
      kind: Service
      name: jaeger
